### ISSUE TITLE
Contact Form for Reach Out Session 

### ISSUE THREAD

**Issue by codyeddie** [codyeddie/run-buddy#2]
# Contact Form for Reach Out Session 

## Contact Requirements 
* Heading: "Contact Us"
* Name: Input Text Field 
* Message: Large message area

**Comment by leonardsangoroh** [comment]
Hi, I would like to make the contact form if you don't mind.
If you're okay with it, kindly provide more Information regarding the contact form like;
-Whether will have its own file or it will be placed within the index.html file
-What colour schemes you want

**Comment by codyeddie** [comment]
Thanks for offering! This is actually for a class assignment that I’m working on so I will be resolving this issue on my own! I appreciate it!

**Comment by leonardsangoroh** [comment]
Sure sure no worries, thanks for the feedback
